import turtle

tao = turtle.Pen()
tao.shape('turtle')

tao.penup()
tao.left(90)
tao.forward(300)
tao.left(90)
tao.forward(300)
tao.left(180)
tao.pendown()

for lamp in range (6):
    tao.forward(100)
    tao.right(90)
    tao.forward(200)
    for light in range (10):
        tao.circle(20)
        tao.left(36)
    tao.penup()
    tao.left(180)
    tao.forward(200)
    tao.right(90)
    tao.pendown()

    
tao.forward(200)
tao.penup()
tao.right(90)
tao.forward(400)
tao.right(90)
tao.forward(100)
tao.pendown()
for chair in range (6):
    tao.right(90)
    tao.forward(50)
    tao.left(90)
    tao.forward(10)
    tao.left(90)
    tao.forward(10)
    tao.right(90)
    tao.forward(40)
    tao.right(90)
    tao.forward(10)
    tao.left(90)
    tao.forward(10)
    tao.left(90)
    tao.forward(50)
    tao.left(90)
    tao.forward(60)
    tao.right(90)
    tao.forward(50)
    tao.right(90)
    tao.forward(10)
    tao.right(90)
    tao.forward(40)
    tao.left(90)
    tao.forward(40)
    tao.left(90)
    tao.forward(40)
    tao.right(90)
    tao.forward(10)
    tao.right(90)
    tao.forward(50)
    tao.left(90)
    tao.penup()
    tao.forward(20)
    tao.pendown()

    
for chair in range (3):
    tao.right(90)
    tao.forward(50)
    tao.left(90)
    tao.forward(10)
    tao.left(90)
    tao.forward(10)
    tao.right(90)
    tao.forward(40)
    tao.right(90)
    tao.forward(10)
    tao.left(90)
    tao.forward(10)
    tao.left(90)
    tao.forward(50)
    tao.left(90)
    tao.forward(60)
    tao.right(90)
    tao.forward(50)
    tao.right(90)
    tao.forward(10)
    tao.right(90)
    tao.forward(40)
    tao.left(90)
    tao.forward(40)
    tao.left(90)
    tao.forward(40)
    tao.right(90)
    tao.forward(10)
    tao.right(90)
    tao.forward(50)
    tao.left(90)
    tao.penup()
    tao.forward(20)
    tao.pendown()

    
